[package]
name = "rust-arcane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fermium = "22401.1.0"
gl33 = "0.2.1"
glm = "0.2.3"